# Generated by Django 5.0.1 on 2024-06-19 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('daily_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
