# Generated by Django 5.0.1 on 2024-06-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_salesstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySales',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
